services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres_primary:
    image: postgres:17
    container_name: postgres_primary
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./conf/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  postgres_replica:
    image: postgres:17
    container_name: postgres_replica
    restart: always
    ports:
      - "5433:5432"
    environment:
      PGPASSWORD: ${REPLICA_PASSWORD}
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./conf/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    depends_on:
      - postgres_primary
    command: >
      bash -c "
        chown -R postgres:postgres /var/lib/postgresql/data && chmod 0700 /var/lib/postgresql/data;
        if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Initializing replica from primary...';
          rm -rf /var/lib/postgresql/data/* || true;
          gosu postgres pg_basebackup -h postgres_primary -D /var/lib/postgresql/data -U replica_user -v -P --wal-method=stream;
          touch /var/lib/postgresql/data/standby.signal;
        fi;
        exec gosu postgres postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
      "

  app1:
    build: ..
    container_name: smart_parking_app1
    environment:
      PARKING_CONSUMER_ENABLED: "true"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SERVER_PORT: 8080
    depends_on:
      - postgres_primary
      - redis

  app2:
    build: ..
    container_name: smart_parking_app2
    environment:
      PARKING_CONSUMER_ENABLED: "false"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SERVER_PORT: 8080
    depends_on:
      - postgres_primary
      - redis

  nginx:
    image: nginx:alpine
    container_name: smart_parking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

volumes:
  primary_data:
  replica_data:
